services:
  app:
    build: .
    ports:
      - "${VITE_PORT}:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_PORT=${VITE_PORT}
      - VITE_API_KEY=${VITE_API_KEY}
      - VITE_API_URL=${VITE_API_URL}
    env_file:
      - .env
    networks:
      - blog
    expose:
      - ${VITE_PORT}
networks:
  blog:
    name: blog
    driver: bridge
    external: true
